site_name: Ryan DaYe (MMing)
site_url: https://168848.xyz
site_description: "python,vps,linux,ios,macos"
repo_url: https://github.com/mming/mming.github.io
repo_name: mming
edit_uri: ""
site_author: mming
copyright: Copyright &copy; 2023 mming - Documentation built with MkDocs (Material theme)
nav:
- index:
  - 首页: index.md
  - 折腾log: log.md
- Documents:
  - python: 
    - about mkdocs: python/mkdocs.md
  - VPS: 
    - 升级centos7的git程序: vps/updateCentos7Git.md
    - tmux快捷键: vps/tmuxCheatSheet.md
    - acme使用: vps/acme.md
    - telegramBot: vps/telegramBot.md
  - Project Manage:
    - 项目管理: project.md
    - 手机投屏: projectManagement/scrcpy.md
    - 字符与字节（mysql）: projectManagement/varchar.md
    - test: 
      - test1: test.md




- About:
  - 关于Ta: about.md

#主题
theme:
  name: simple-blog
  theme_style: dark
  components:
    footer: false
    preview: true
    site_name: true
    title: true
    menu: true



# theme:
#   name: 'material'
#   language: 'zh'  # 配置语言
#   search_index_only: true
#   palette:  # 颜色
#     # Palette toggle for light mode
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       # primary: light blue
#       toggle:
#         icon: material/weather-sunny
#         name: Switch to dark mode

#     # Palette toggle for dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       # primary: blue grey
#       toggle:
#         icon: material/weather-night
#         name: Switch to light mode
#     # - media: "(prefers-color-scheme: light)"
#     #   scheme: default
#     #   toggle:
#     #     icon: material//weather-sunny
#     #     name: Switch to dark mode
#     # - media: "(prefers-color-scheme: dark)"
#     #   primary: teal
#     #   scheme: slate
#     #   toggle:
#     #     icon: material/weather-night
#     #     name: Switch to light mode
#     # primary: 'light blue'
#     #- accent: 'indigo'

#   features:
#     #- tabs: true  # 横向导航
#     - navigation.instant # 点击内部链接时，不用全部刷新页面
#     - navigation.tracking # 在url中使用标题定位锚点Anchor tracking
#     - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
#     - navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
#     - navigation.sections # nav节点缩进
#     - navigation.expand # 不折叠左侧nav节点
#     # - navigation.indexes # 指定节点index pages ，跟instant不兼容
#     - toc.integrate # 右侧生产目录,This feature flag is not compatible with navigation.indexes, as sections cannot host the table of contents due to missing space.
#     # - toc.integrate #导航集成
#     - navigation.top # 一键回顶部
#     - header.autohide
#     - search.share # 搜索分享
#     - search.suggest # 搜索建议
#     - search.highlight #搜索高亮
#     - content.code.annotate
#   custom_dir: 'docs/resources/'
    

#   #图标
#   icon:
#     logo: material/library-shelves #change any site icon bundled with the theme
#     admonition:
#       note: octicons/tag-16
#       abstract: octicons/checklist-16
#       info: octicons/info-16
#       tip: octicons/squirrel-16
#       success: octicons/check-16
#       question: octicons/question-16
#       warning: octicons/alert-16
#       failure: octicons/x-circle-16
#       danger: octicons/zap-16
#       bug: octicons/bug-16
#       example: octicons/beaker-16
#       quote: octicons/quote-16

# # 扩展

# markdown_extensions:
#   - admonition  # 提示块
#   - footnotes  # 脚注
#   - meta  # 定义元数据，通过文章上下文控制，如disqus
#   - pymdownx.caret  # 下划线上标
#   - pymdownx.tilde  # 删除线下标
#   - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
#   - pymdownx.details  # 提示块可折叠
#   - pymdownx.inlinehilite  # 行内代码高亮
#   - pymdownx.mark  # 文本高亮
#   - pymdownx.smartsymbols  # 符号转换
#   - pymdownx.superfences  # 代码嵌套在列表里
#   - pymdownx.snippets
#   - pymdownx.highlight:
#       anchor_linenums: true
# #  - pymdownx.arithmatex  # 数学公式
#   - pymdownx.betterem:  # 对加粗和斜体更好的检测
#       smart_enable: all
# #  - pymdownx.emoji:  # 表情
# #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
# #  - pymdownx.magiclink  # 自动识别超链接
#   - pymdownx.tasklist:  # 复选框checklist
#       custom_checkbox: true
#   # - codehilite:    # 代码高亮，显示行号
#   #     guess_lang: false
#   #     linenums: true
#   - toc:  # 锚点
#       permalink: true
#   - abbr
#   - def_list
#   - tables
#   - attr_list
#   - md_in_html

# plugins:
#   - search:
#       separator: '[\s\u200b\-]'


# #扩展样式
# # extra_css:
# #   - resources/css/extra.css

# # 自定义css 扩展样式
# extra_css:
#   - stylesheets/extra.css
#   # - '//cdn.staticaly.com/gh/codeslive/cdn@main/css/imageszoom.css' #图片放大css
#   #- '//cdn.staticaly.com/gh/codeslive/images-pages@main/cdn/css/custom.css'
#   #- '//cdn.staticaly.com/gh/codeslive/images-pages@main/cdn/css/simplelightbox.min.css' #图片放大css

# # 自定义js
# extra_javascript: 
#   #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/busuanzi.pure.mini.js' # 网站访问统计
#   - 'assets/js/busuanzi.pure.mini.js'
#   # - '//cdn.staticaly.com/gh/codeslive/cdn@main/js/imageszoom.js' # 图片放大js
#   #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/jquery-3.2.1.min.js' 
#   #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/simplelightbox.min.js'  #图片放大js
#   #- '//cdn.staticaly.com/gh/codeslive/cdn@main/js/custom.js'


# # 设置
# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/mming
#       name: github
#     - icon: fontawesome/brands/slack
#       link: https://mming.github.io
#       name: myblog
#     - icon: fontawesome/solid/paper-plane
#       link: 0x.mming@gmail.com
#       name: email
#   # consent:
#   #   title: Cookie consent
#   #   description: >- 
#   #     We use cookies to recognize your repeated visits and preferences, as well
#   #     as to measure the effectiveness of our documentation and whether users
#   #     find what they're searching for. With your consent, you're helping us to
#   #     make our documentation better.
#   #   cookies:
#   #     analytics:
#   #       name: Google Analytics
#   #       checked: false
#   #   actions:
#   #     - accept
#   #     - manage 